nome = ['henrique','milena','sophia','miguel']
for nomes in nome:
print(nomes)


#esse erro ocorre por causa da identação


